
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 75
#define YY_END_OF_BUFFER 76
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[382] =
    {   0,
        0,    0,    0,    0,   15,   15,    0,    0,   76,   74,
       72,   73,   72,   51,   21,   71,   53,   74,   57,   47,
       65,   49,   64,   54,   74,   63,   12,   13,   45,   55,
       66,   60,   71,   71,   56,   46,   41,   70,   71,   71,
       71,   71,   71,   71,   71,   71,   71,   71,   71,   71,
       71,   71,   71,   71,   59,   74,   48,   22,   24,   23,
       22,   15,   75,   17,   19,   20,    0,    1,   52,   71,
       67,   70,   44,    7,    0,   14,   18,    1,   13,    0,
        1,   13,    2,    0,   43,   58,   62,   61,   42,   71,
       71,   71,   71,   71,   71,   71,   71,   71,   71,   71,

       71,   71,   71,   70,   71,   71,   71,   71,   71,   71,
       71,   71,   35,   71,   71,   71,   71,   71,   71,   71,
       71,   71,   71,   71,   71,   71,   71,   71,   71,   71,
       71,   71,   50,   25,   15,   16,    0,    0,    7,    4,
        0,    0,    2,    0,    0,    2,    3,    3,    0,    3,
        3,    3,    2,    1,    2,    2,   71,   71,   71,   71,
       71,   71,   71,   71,   71,   71,   71,   71,   71,   71,
       71,   71,   71,   71,   71,   71,   71,   70,   71,   71,
       71,   34,   71,   71,   71,   71,   71,   71,   71,   71,
       71,   71,   71,   71,   71,   71,   71,   71,   71,   71,

       71,   71,   71,    0,    4,   11,    4,    0,    4,    4,
        0,    2,    6,    2,    0,    2,    3,    3,    3,   10,
        3,    0,    3,    3,    3,    3,    3,   71,   71,   71,
       71,   71,   71,   71,   71,   71,   71,   71,   71,   71,
       36,   71,   71,   71,   71,   71,   71,   71,   71,   71,
       71,   71,   71,   71,   71,   71,   71,   71,   71,   71,
       71,   71,   71,   68,   27,   71,   71,    4,    0,    4,
        9,    0,    5,    3,    0,    3,    8,    3,    3,    3,
       71,   71,   71,   71,   71,   71,   39,   71,   71,   71,
       71,   69,   70,   71,   71,   71,   71,   71,   71,   71,

       71,   71,   71,   71,   71,   71,   71,   70,   71,   71,
       26,    9,    0,    8,   71,   28,   70,   71,   71,   71,
       71,   37,   71,   71,   71,   71,   71,   71,   71,   71,
       31,   30,   29,   71,   71,   71,   71,   38,   70,    0,
       71,   40,   71,   71,   71,   71,   71,   71,   71,   71,
       71,    0,    0,   71,   71,   71,   71,   71,   71,    0,
        0,   71,   71,   71,    0,    0,   71,    0,    0,   71,
        0,    0,    0,    0,    0,    0,    0,    0,   32,   33,
        0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    1,    7,    8,    9,    1,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   19,
       19,   19,   19,   19,   19,   19,   19,    1,   20,   21,
       22,   23,    1,    1,    7,    7,    7,    7,   24,    7,
        7,    7,   25,    7,    7,    7,    7,    7,    7,    7,
        7,    7,   26,    7,    7,    7,    7,    7,    7,    7,
       27,   28,   29,   30,   31,    1,   32,   33,   34,   35,

       36,   37,   38,   39,   40,    7,   41,   42,   43,   44,
       45,   46,    7,   47,   48,   49,   50,   51,   52,   53,
       54,   55,   56,   57,   58,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[59] =
    {   0,
        1,    1,    2,    1,    1,    3,    4,    1,    1,    1,
        1,    2,    1,    1,    1,    1,    1,    4,    4,    1,
        1,    1,    1,    4,    4,    4,    1,    1,    1,    1,
        4,    4,    4,    4,    4,    4,    5,    4,    4,    4,
        4,    4,    4,    5,    4,    4,    5,    4,    5,    4,
        4,    4,    4,    4,    4,    1,    1,    1
    } ;

static const flex_int16_t yy_base[388] =
    {   0,
        0,    0,   56,   57,   58,   61,  677,  676,  678,  681,
      681,  681,   61,  655,  681,    0,  681,  667,  681,  681,
      681,  662,  681,   51,   63,   59,   71,  125,  681,   47,
      652,   73,  629,   29,  681,  681,  681,   82,   55,   52,
       72,   71,   66,   90,  627,   90,  626,  110,  104,  634,
       98,   76,  624,  629,  681,  149,  681,  681,  681,  681,
        0,    0,  681,  650,  681,  681,  153,  681,  681,    0,
      681,  681,  681,  207,  630,  681,  681,  155,  646,  159,
      261,  645,  315,  172,  681,  681,  681,  681,  681,  614,
      615,  613,  177,  612,  611,  613,  621,  607,   76,  623,

      622,  609,  615,  601,  602,  599,  599,  605,  602,  600,
      597,  594,    0,  596,  114,  597,  591,  587,  596,  603,
       81,  603,  586,  589,  123,  587,  592,  587,  136,  147,
       51,  590,  198,  681,    0,  681,  214,  209,    0,  369,
      226,  585,  606,  231,  606,  242,    0,  252,  263,    0,
      423,  285,  582,  292,  581,    0,  563,  558,  547,  546,
      558,  551,  560,  554,  553,  554,  540,  538,  150,  553,
      551,  547,  539,  544,  531,  546,  545,    0,  530,   67,
      525,  537,  532,  529,  526,  526,  515,  512,  518,  507,
      509,  505,  510,  512,  498,  511,  491,  492,  491,  495,

      494,  495,  484,  504,  322,  317,    0,  339,    0,    0,
      480,  498,  346,  350,  371,  393,  400,  404,  433,  425,
        0,  444,    0,    0,    0,    0,  454,  478,  470,  474,
      461,  460,  469,  458,  458,  447,  440,  447,  436,  436,
        0,  432,  438,  429,  421,  432,  420,  434,  418,  409,
      423,  421,  410,  405,  393,  385,  393,  398,  383,  391,
      382,  365,  368,    0,    0,  366,  378,  465,  473,  484,
      475,  364,  494,  505,  515,  524,  534,    0,    0,    0,
      374,  368,  358,  367,  349,  363,    0,  350,  350,  355,
      351,    0,  341,  337,  329,  332,  334,  331,  325,  313,

      327,  326,  315,  322,  306,  313,  300,  297,  304,  297,
        0,  540,  293,  545,  282,    0,  311,  291,  280,  272,
      268,    0,  267,  260,  277,  278,  276,  271,  270,  256,
        0,    0,    0,  265,  250,  257,  249,  681,  274,  242,
      237,    0,  248,  234,  239,  238,  233,  217,  215,  213,
      218,  207,  202,  202,  203,  211,  202,  196,  175,  189,
      170,  170,  178,  154,  160,  189,  168,  155,  154,  159,
      156,  142,  141,  124,  114,  101,   82,   23,  681,  681,
      681,  602,  607,  612,  614,  619,  623
    } ;

static const flex_int16_t yy_def[388] =
    {   0,
      381,    1,  382,  382,  383,  383,  384,  384,  381,  381,
      381,  381,  381,  381,  381,  385,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  385,  385,  381,  381,  381,  385,  385,  385,
      385,  385,  385,  385,  385,  385,  385,  385,  385,  385,
      385,  385,  385,  385,  381,  381,  381,  381,  381,  381,
      386,  387,  381,  381,  381,  381,  381,  381,  381,  385,
      381,  381,  381,  381,  381,  381,  381,  381,   28,  381,
      381,   28,  381,  381,  381,  381,  381,  381,  381,  385,
      385,  385,  385,  385,  385,  385,  385,  385,  385,  385,

      385,  385,  385,  385,  385,  385,  385,  385,  385,  385,
      385,  385,  385,  385,  385,  385,  385,  385,  385,  385,
      385,  385,  385,  385,  385,  385,  385,  385,  385,  385,
      385,  385,  381,  381,  387,  381,  381,  381,   74,  381,
      381,  381,   83,  381,  381,  381,   81,  381,  381,   81,
      381,  381,   83,   81,   83,   83,  385,  385,  385,  385,
      385,  385,  385,  385,  385,  385,  385,  385,  385,  385,
      385,  385,  385,  385,  385,  385,  385,  385,  385,  385,
      385,  385,  385,  385,  385,  385,  385,  385,  385,  385,
      385,  385,  385,  385,  385,  385,  385,  385,  385,  385,

      385,  385,  385,  381,  381,  381,  140,  381,  140,  140,
      381,   83,  381,  381,  381,  381,  381,  381,  381,  381,
      151,  381,  151,  151,  154,  154,  151,  385,  385,  385,
      385,  385,  385,  385,  385,  385,  385,  385,  385,  385,
      385,  385,  385,  385,  385,  385,  385,  385,  385,  385,
      385,  385,  385,  385,  385,  385,  385,  385,  385,  385,
      385,  385,  385,  385,  385,  385,  385,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  227,  227,  227,
      385,  385,  385,  385,  385,  385,  385,  385,  385,  385,
      385,  385,  385,  385,  385,  385,  385,  385,  385,  385,

      385,  385,  385,  385,  385,  385,  385,  385,  385,  385,
      385,  381,  381,  381,  385,  385,  385,  385,  385,  385,
      385,  385,  385,  385,  385,  385,  385,  385,  385,  385,
      385,  385,  385,  385,  385,  385,  385,  381,  385,  381,
      385,  385,  385,  385,  385,  385,  385,  385,  385,  385,
      385,  381,  381,  385,  385,  385,  385,  385,  385,  381,
      381,  385,  385,  385,  381,  381,  385,  381,  381,  385,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
        0,  381,  381,  381,  381,  381,  381
    } ;

static const flex_int16_t yy_nxt[740] =
    {   0,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
       20,   21,   22,   23,   24,   25,   26,   27,   28,   29,
       30,   31,   32,   16,   33,   34,   35,   10,   36,   37,
       38,   39,   40,   41,   42,   43,   44,   45,   16,   46,
       16,   47,   16,   48,   16,   49,   50,   51,   52,   16,
       53,   54,   16,   16,   16,   55,   56,   57,   59,   59,
       63,   60,   60,   63,   67,   72,   74,   85,   86,   64,
       76,  380,   64,   73,   67,   77,   68,   91,   67,   67,
       74,   74,   92,   61,   61,   67,   78,   94,   67,   67,
      201,   67,  202,   74,   88,   89,   96,   68,   97,   93,

       93,   67,   95,   99,   75,   98,  103,  105,  246,  106,
      100,  247,   93,  101,  129,  104,  102,   67,  107,   74,
      187,  108,  130,  165,  166,  188,  113,   67,   79,  109,
      379,  110,  114,  115,  111,  120,  124,   80,   67,   80,
       81,  117,   82,   83,  378,  118,  125,  126,   84,  127,
      121,  128,   67,  122,  192,   79,   67,  377,   74,  119,
       84,  181,  182,  376,   68,  375,   67,   67,   68,  193,
       67,   67,   74,   74,  144,  197,  145,  146,  199,   67,
       67,   79,  198,   67,   80,   74,   80,  144,  374,  145,
      146,  373,   68,  178,   93,   93,  200,  237,  238,  372,

      178,   67,  371,  370,  369,  133,  368,   93,  367,   67,
       74,   74,  206,   68,  178,   67,   67,  178,  366,  137,
      365,  137,  138,  178,  139,  140,  206,  206,   67,  138,
      141,  204,  205,   67,  213,  364,  178,   74,  137,  206,
      137,  138,  141,  204,  205,  214,  178,  363,  213,  213,
      362,  361,  360,  178,   67,  217,  359,  215,  358,  214,
      216,  213,  178,   74,  147,  206,  220,  149,  357,  218,
      219,  356,  214,  148,  355,  148,  149,  354,  150,  151,
      220,  220,  217,  178,  152,  178,  353,  213,  217,  352,
      351,  147,  350,  220,  349,  225,  152,  148,  214,  148,

      149,  348,  218,  219,  347,  178,  178,  346,  217,  226,
      227,  345,  344,  178,  178,  217,  178,  147,  153,  220,
      206,  343,  225,  342,  341,  268,  340,   80,  339,   80,
      154,  338,  155,  156,  206,  206,  337,  269,   84,  268,
      270,  217,  271,  336,  178,  153,  335,  206,  225,  213,
       84,  178,  268,  214,  334,  333,  271,  271,  332,  331,
      330,  329,  328,  213,  213,  215,  178,  214,  214,  271,
      327,  153,  207,  206,  273,  326,  213,  178,  268,  325,
      214,  137,  324,  137,  208,  323,  209,  210,  273,  273,
      322,  321,  141,  320,  319,  271,  214,  178,  318,  207,

      317,  273,  213,  217,  141,  316,  214,  217,  215,  315,
      214,  216,  313,  311,  310,  309,  308,  217,  217,  149,
      307,  217,  217,  214,  306,  207,  221,  273,  220,  178,
      217,  305,  304,  178,  217,  148,  274,  148,  222,  303,
      223,  224,  220,  220,  302,  301,  152,  277,  275,  214,
      274,  276,  300,  221,  299,  220,  217,  278,  152,  298,
      217,  277,  277,  274,  297,  296,  295,  294,  268,  178,
      293,  279,  280,  292,  277,  291,  312,  290,  271,  221,
      269,  220,  268,  268,  278,  289,  288,  268,  178,  274,
      312,  312,  271,  271,  287,  268,  178,  273,  178,  269,

      277,  268,  270,  312,  286,  271,  285,  284,  274,  283,
      278,  273,  273,  282,  268,  281,  212,  272,  314,  138,
      275,  268,  274,  274,  273,  267,  266,  274,  265,  312,
      264,  271,  314,  314,  263,  274,  262,  277,  178,  275,
      268,  274,  276,  312,  261,  314,  260,  259,  314,  258,
      273,  277,  277,  257,  274,  256,  255,  312,  312,  254,
      253,  274,  314,  314,  277,  252,  251,  178,  250,  178,
      312,  314,  249,  248,  178,  314,  245,  244,  243,  242,
      274,  178,  241,  240,  239,  236,  178,  235,  178,  178,
      277,  234,  233,  232,  231,  230,  312,  229,  228,  212,

      212,  314,   58,   58,   58,   58,   58,   62,   62,   62,
       62,   62,   65,   65,   65,   65,   65,   70,   70,  134,
      134,  144,  134,  135,  212,  135,  135,  135,  211,  203,
      196,  195,  194,  191,  190,  189,  186,  185,  178,  184,
      183,  180,  179,  178,  177,  176,  175,  174,  173,  172,
      171,  170,  169,  168,  167,  164,  163,  162,  161,  160,
      159,  158,  157,  143,  143,  142,  136,  132,  131,  123,
      116,  112,   90,   87,   72,   71,   69,  381,   66,   66,
        9,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,

      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381
    } ;

static const flex_int16_t yy_chk[740] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    3,    4,
        5,    3,    4,    6,   13,   24,   25,   30,   30,    5,
       26,  378,    6,   24,   27,   26,   13,   34,   13,   13,
       25,   25,   34,    3,    4,   38,   27,   39,   27,   27,
      131,   13,  131,   25,   32,   32,   40,   38,   40,   38,

       38,   27,   39,   41,   25,   40,   42,   43,  180,   43,
       41,  180,   38,   41,   52,   42,   41,   13,   43,   25,
      121,   44,   52,   99,   99,  121,   46,   27,   28,   44,
      377,   44,   46,   46,   44,   49,   51,   28,   38,   28,
       28,   48,   28,   28,  376,   48,   51,   51,   28,   51,
       49,   51,   56,   49,  125,   28,   67,  375,   78,   48,
       28,  115,  115,  374,   56,  373,   56,   56,   67,  125,
       67,   67,   78,   78,   80,  129,   80,   80,  130,   56,
       93,   28,  129,   67,   84,   78,   84,   84,  372,   84,
       84,  371,   93,  370,   93,   93,  130,  169,  169,  369,

      130,  133,  368,  367,  366,   56,  365,   93,  364,   67,
       74,   78,  138,  133,  363,  133,  133,  362,  361,   74,
      360,   74,   74,  359,   74,   74,  138,  138,  133,  137,
       74,  137,  137,   93,  144,  358,  357,   74,  141,  138,
      141,  141,   74,  141,  141,  146,  356,  355,  144,  144,
      354,  353,  352,  351,  133,  148,  350,  146,  349,  146,
      146,  144,  348,   74,   81,  138,  149,  148,  347,  148,
      148,  346,  146,   81,  345,   81,   81,  344,   81,   81,
      149,  149,  148,  343,   81,  341,  340,  144,  152,  339,
      337,   81,  336,  149,  335,  154,   81,  152,  146,  152,

      152,  334,  152,  152,  330,  329,  328,  327,  148,  154,
      154,  326,  325,  324,  323,  152,  321,   81,   83,  149,
      206,  320,  154,  319,  318,  205,  317,   83,  315,   83,
       83,  313,   83,   83,  206,  206,  310,  205,   83,  205,
      205,  152,  208,  309,  308,   83,  307,  206,  154,  213,
       83,  306,  205,  214,  305,  304,  208,  208,  303,  302,
      301,  300,  299,  213,  213,  214,  298,  214,  214,  208,
      297,   83,  140,  206,  215,  296,  213,  295,  205,  294,
      214,  140,  293,  140,  140,  291,  140,  140,  215,  215,
      290,  289,  140,  288,  286,  208,  216,  285,  284,  140,

      283,  215,  213,  217,  140,  282,  214,  218,  216,  281,
      216,  216,  272,  267,  266,  263,  262,  217,  217,  218,
      261,  218,  218,  216,  260,  140,  151,  215,  220,  259,
      217,  258,  257,  256,  218,  151,  219,  151,  151,  255,
      151,  151,  220,  220,  254,  253,  151,  222,  219,  216,
      219,  219,  252,  151,  251,  220,  217,  227,  151,  250,
      218,  222,  222,  219,  249,  248,  247,  246,  268,  245,
      244,  227,  227,  243,  222,  242,  269,  240,  271,  151,
      268,  220,  268,  268,  227,  239,  238,  270,  237,  219,
      269,  269,  271,  271,  236,  268,  235,  273,  234,  270,

      222,  270,  270,  269,  233,  271,  232,  231,  274,  230,
      227,  273,  273,  229,  270,  228,  212,  211,  275,  204,
      274,  268,  274,  274,  273,  203,  202,  276,  201,  269,
      200,  271,  275,  275,  199,  274,  198,  277,  197,  276,
      270,  276,  276,  312,  196,  275,  195,  194,  314,  193,
      273,  277,  277,  192,  276,  191,  190,  312,  312,  189,
      188,  274,  314,  314,  277,  187,  186,  185,  184,  183,
      312,  275,  182,  181,  179,  314,  177,  176,  175,  174,
      276,  173,  172,  171,  170,  168,  167,  166,  165,  164,
      277,  163,  162,  161,  160,  159,  312,  158,  157,  155,

      153,  314,  382,  382,  382,  382,  382,  383,  383,  383,
      383,  383,  384,  384,  384,  384,  384,  385,  385,  386,
      386,  145,  386,  387,  143,  387,  387,  387,  142,  132,
      128,  127,  126,  124,  123,  122,  120,  119,  118,  117,
      116,  114,  112,  111,  110,  109,  108,  107,  106,  105,
      104,  103,  102,  101,  100,   98,   97,   96,   95,   94,
       92,   91,   90,   82,   79,   75,   64,   54,   53,   50,
       47,   45,   33,   31,   22,   18,   14,    9,    8,    7,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,

      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381,  381,
      381,  381,  381,  381,  381,  381,  381,  381,  381
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "jucompiler.l"
#line 2 "jucompiler.l"
#include <stdio.h>
#include <stdlib.h>
    int nline = 1;
    int column = 1;

    char buffer[128];
    char *s;


  void resetline(){
  	nline++;
	column=1;
}
void updatecol(int n){
    column +=n;
}  
    
#line 747 "lex.yy.c"

#line 749 "lex.yy.c"

#define INITIAL 0
#define STRING 1
#define COMMENT 2
#define COMMENT_1 3

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 36 "jucompiler.l"

#line 971 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 382 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 681 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 37 "jucompiler.l"
{printf("REALLIT(%s)\n",yytext);}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 39 "jucompiler.l"
{printf("REALLIT(%s)\n",yytext);}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 40 "jucompiler.l"
{printf("REALLIT(%s)\n",yytext);}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 41 "jucompiler.l"
{printf("REALLIT(%s)\n",yytext);}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 42 "jucompiler.l"
{printf("REALLIT(%s)\n",yytext);}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 43 "jucompiler.l"
{printf("REALLIT(%s)\n",yytext);}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 44 "jucompiler.l"
{printf("REALLIT(%s)\n",yytext);}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 45 "jucompiler.l"
{printf("REALLIT(%s)\n",yytext);}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 46 "jucompiler.l"
{printf("REALLIT(%s)\n",yytext);}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 47 "jucompiler.l"
{printf("REALLIT(%s)\n",yytext);}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 48 "jucompiler.l"
{printf("REALLIT(%s)\n",yytext);}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 50 "jucompiler.l"
{printf("INTLIT(0)\n");}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 51 "jucompiler.l"
{printf("INTLIT(%s)\n",yytext);}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 54 "jucompiler.l"
BEGIN COMMENT;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 55 "jucompiler.l"
nline++;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 56 "jucompiler.l"
BEGIN INITIAL;          //Finaliza o comentario
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 57 "jucompiler.l"
//ignora
	YY_BREAK
case YY_STATE_EOF(COMMENT):
#line 58 "jucompiler.l"
{printf("Line %d, column %d: unterminated comment\n",nline, column);BEGIN 0;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 60 "jucompiler.l"
{BEGIN COMMENT_1;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 61 "jucompiler.l"

	YY_BREAK
case 20:
/* rule 20 can match eol */
YY_RULE_SETUP
#line 62 "jucompiler.l"
{BEGIN 0; resetline();}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 64 "jucompiler.l"
{BEGIN STRING;s = buffer;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 65 "jucompiler.l"
{*s ++ = *yytext; column+=yyleng;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 66 "jucompiler.l"
{BEGIN 0;*s = 0;printf("STRLIT(\"%s\")\n",buffer);}
	YY_BREAK
case 24:
/* rule 24 can match eol */
YY_RULE_SETUP
#line 67 "jucompiler.l"
{BEGIN 0;printf("Line %d,col %d:unterminated string literal\n",nline,column);}
	YY_BREAK
case 25:
/* rule 25 can match eol */
YY_RULE_SETUP
#line 68 "jucompiler.l"
{*s = 0;printf("Line %d, col %d: invalid escape sequence (%s)\n",nline,column,yytext);}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 71 "jucompiler.l"
{printf("WHILE\n");}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 72 "jucompiler.l"
{printf("VOID\n");}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 73 "jucompiler.l"
{printf("STRING\n");}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 74 "jucompiler.l"
{printf("STATIC\n");}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 75 "jucompiler.l"
{printf("RETURN\n");}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 76 "jucompiler.l"
{printf("PUBLIC\n");}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 77 "jucompiler.l"
{printf("PARSEINT\n");}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 78 "jucompiler.l"
{printf("PRINT\n");}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 79 "jucompiler.l"
{printf("INT\n");}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 80 "jucompiler.l"
{printf("IF\n");}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 81 "jucompiler.l"
{printf("ELSE\n");}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 82 "jucompiler.l"
{printf("DOUBLE\n");}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 83 "jucompiler.l"
{printf("DOTLENGTH\n");}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 84 "jucompiler.l"
{printf("CLASS\n");}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 85 "jucompiler.l"
{printf("BOOL\n");}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 86 "jucompiler.l"
{printf("XOR\n");}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 87 "jucompiler.l"
{printf("RSHIFT\n");}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 88 "jucompiler.l"
{printf("LSHIFT\n");}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 89 "jucompiler.l"
{printf("ARROW\n");}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 90 "jucompiler.l"
{printf("SEMICOLON\n");}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 91 "jucompiler.l"
{printf("RSQ\n");}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 92 "jucompiler.l"
{printf("RPAR\n");}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 93 "jucompiler.l"
{printf("RBRACE\n");}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 94 "jucompiler.l"
{printf("PLUS\n");}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 95 "jucompiler.l"
{printf("OR\n");}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 96 "jucompiler.l"
{printf("NOT\n");}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 97 "jucompiler.l"
{printf("NE\n");}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 98 "jucompiler.l"
{printf("MOD\n");}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 99 "jucompiler.l"
{printf("MINUS\n");}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 100 "jucompiler.l"
{printf("LT\n");}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 101 "jucompiler.l"
{printf("LSQ\n");}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 102 "jucompiler.l"
{printf("LPAR\n");}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 103 "jucompiler.l"
{printf("LE\n");}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 104 "jucompiler.l"
{printf("LBRACE\n");}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 105 "jucompiler.l"
{printf("GT\n");}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 106 "jucompiler.l"
{printf("GE\n");}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 107 "jucompiler.l"
{printf("EQ\n");}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 108 "jucompiler.l"
{printf("DIV\n");}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 109 "jucompiler.l"
{printf("COMMA\n");}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 110 "jucompiler.l"
{printf("STAR\n");}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 111 "jucompiler.l"
{printf("ASSIGN\n");}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 112 "jucompiler.l"
{printf("AND\n");}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 113 "jucompiler.l"
{printf("BOOLLIT\n");}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 114 "jucompiler.l"
{printf("BOOLLIT\n");}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 115 "jucompiler.l"
{printf("RESERVED\n");}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 116 "jucompiler.l"
{printf("ID(%s)\n",yytext);}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 118 "jucompiler.l"
{updatecol(yyleng);}
	YY_BREAK
case 73:
/* rule 73 can match eol */
YY_RULE_SETUP
#line 119 "jucompiler.l"
{resetline();}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 120 "jucompiler.l"
{printf("Line %d, column %d: illegal character (%s)\n",nline,column,yytext);updatecol(yyleng);}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 122 "jucompiler.l"
ECHO;
	YY_BREAK
#line 1411 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(STRING):
case YY_STATE_EOF(COMMENT_1):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 382 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 382 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 381);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 122 "jucompiler.l"

int main(int argc, char *argv[ ]){
    if(argc==2){
        char * str = "-l";
        if(strcmp(argv[1],str)==0){
            //state=1;
        }
    }
    yylex();
    return 0;
}

int yywrap(){
    return 1;
}

