
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	(yytext_ptr) -= (yy_more_len); \
	yyleng = (int) (yy_cp - (yytext_ptr)); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 79
#define YY_END_OF_BUFFER 80
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[407] =
    {   0,
       76,   76,    0,    0,    0,    0,    0,    0,   80,   78,
       76,   77,   77,   56,   25,   75,   58,   78,   62,   52,
       70,   54,   69,   59,   78,   68,    2,    4,   50,   60,
       71,   65,   75,   75,   61,   51,   46,   75,   75,   75,
       75,   75,   75,   75,   75,   75,   75,   75,   75,   75,
       75,   75,   75,   75,   64,   78,   53,   26,   29,   26,
       28,   26,   23,   24,   23,   19,   20,   76,   77,   57,
       75,   72,    1,   49,   13,    0,    0,   21,   18,    5,
        0,    0,    5,    3,    3,    0,    0,   48,   63,   67,
       66,   47,   75,   75,   75,    5,   75,   75,   75,   75,

       75,   75,   75,   75,   75,   75,   75,    1,   75,   75,
       75,   75,   75,   75,   75,   75,   40,   75,   75,   75,
       75,   75,   75,   75,   75,   75,   75,   75,   75,   75,
       75,   75,   75,   75,   75,   75,   55,   30,   27,   27,
       22,    0,    0,   12,   12,    0,   12,   12,    0,    0,
        0,    7,    0,    0,    8,    8,    0,    0,    3,    5,
        3,    3,    0,   75,   75,   75,   75,   75,   75,   75,
       75,   75,   75,   75,   75,   75,   75,   75,   75,   75,
       75,   75,   75,   75,    1,   75,   75,   75,   39,   75,
       75,   75,   75,   75,   75,   75,   75,   75,   75,   75,

       75,   75,   75,   75,   75,   75,   75,   75,   75,   75,
        0,    0,    0,    0,    9,    9,    0,    9,    9,    0,
        0,    0,    6,    6,    0,    8,    8,    0,    0,    8,
        8,    0,    8,    8,    0,    3,    8,    8,    0,   75,
       75,   75,   75,   75,   75,   75,   75,   75,   75,   75,
       75,   75,   41,   75,   75,   75,   75,   75,   75,   75,
       75,   75,   75,   75,   75,   75,   75,   75,   75,   75,
       75,   75,   75,   75,   75,   73,   32,   75,   75,    0,
        9,    9,    0,   17,    0,    0,   11,    0,    8,    0,
        8,    8,    0,   16,    0,    8,    8,    8,    8,    0,

       75,   75,   75,   75,   75,   75,   44,   75,   75,   75,
       75,   74,    1,   75,   75,   75,   75,   75,   75,   75,
       75,   75,   75,   75,   75,   75,   75,    1,   75,   75,
       31,    0,   15,    0,   10,    0,   14,   75,   33,    1,
       75,   75,   75,   75,   42,   75,   75,   75,   75,   75,
       75,   75,   75,   36,   35,   34,   75,   75,   75,   75,
       15,   43,   14,    1,    0,   75,   45,   75,   75,   75,
       75,   75,   75,   75,   75,   75,    0,    0,   75,   75,
       75,   75,   75,   75,    0,    0,   75,   75,   75,    0,
        0,   75,    0,    0,   75,    0,    0,    0,    0,    0,

        0,    0,    0,   37,   38,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    1,    7,    8,    9,    1,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   19,
       19,   19,   19,   19,   19,   19,   19,    1,   20,   21,
       22,   23,    1,    1,    7,    7,    7,    7,   24,    7,
        7,    7,   25,    7,    7,    7,    7,    7,    7,    7,
        7,    7,   26,    7,    7,    7,    7,    7,    7,    7,
       27,   28,   29,   30,   31,    1,   32,   33,   34,   35,

       36,   37,   38,   39,   40,    7,   41,   42,   43,   44,
       45,   46,    7,   47,   48,   49,   50,   51,   52,   53,
       54,   55,   56,   57,   58,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[59] =
    {   0,
        1,    1,    1,    1,    1,    1,    2,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    2,    2,    1,
        1,    1,    1,    2,    2,    2,    1,    1,    1,    1,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    1,    1,    1
    } ;

static const flex_int16_t yy_base[412] =
    {   0,
        0,    0,   56,   60,   58,   62,  686,  685,  687,  690,
       65,  690,  683,  663,   66,    0,  690,  675,  690,  690,
      690,  670,  690,   54,   60,   63,   67,  112,  690,   60,
      660,   67,  637,   38,  690,  690,  690,   77,   61,   52,
       68,   67,   76,  100,  635,   78,  634,   69,   91,  642,
      100,  108,  632,  637,  690,  140,  690,  690,  690,  672,
      690,  129,  690,  690,  657,  690,  690,  131,  690,  690,
        0,  690,  690,  690,  185,  142,  637,  690,  690,  149,
      156,  146,  230,  653,  275,  166,  652,  690,  690,  690,
      690,  690,  621,  622,  620,  690,  174,  619,  618,  620,

      628,  614,  140,  630,  629,  616,  622,  608,  609,  606,
      606,  612,  609,  607,  604,  601,    0,  603,  146,  604,
      598,  594,  603,  610,   71,  610,  593,  596,  164,  594,
      599,  594,  104,  170,  168,  597,  196,  690,  690,  690,
      690,  207,  199,    0,  320,  219,    0,  210,  592,  221,
      619,  239,  244,  246,  232,  365,  266,    0,  615,  255,
      614,    0,  613,  595,  590,  580,  579,  591,  584,  593,
      588,  587,  588,  574,  572,  219,  587,  585,  581,  573,
      579,  566,  581,  580,    0,  566,   31,  561,  573,  570,
      567,  564,  564,  553,  554,  560,  551,  553,  550,  558,

      561,  547,  561,  546,  548,  548,  555,  555,  557,  546,
      571,  286,  289,  291,    0,    0,    0,    0,    0,  548,
      295,  297,  311,  331,  341,  345,  351,  322,  355,    0,
        0,  372,    0,    0,    0,  566,  253,  374,    0,  546,
      539,  546,  534,  533,  543,  537,  538,  528,  526,  534,
      523,  530,    0,  527,  534,  527,  519,  531,  519,  533,
      517,  512,  530,  529,  515,  510,  502,  498,  506,  511,
      497,  509,  503,  488,  491,    0,    0,  488,  500,  376,
      395,  399,  405,  401,  409,  486,  416,  419,  423,  426,
      430,  451,  459,  441,  466,    0,    0,    0,    0,    0,

      498,  495,  488,  497,  479,  493,    0,  480,  479,  484,
      484,    0,  476,  474,  462,  463,  468,  460,  457,  437,
      447,  445,  430,  437,  419,  426,  417,  415,  415,  413,
        0,  470,  473,  412,  475,  481,  484,  396,    0,  423,
      391,  372,  360,  360,    0,  358,  350,  364,  365,  365,
      351,  349,  326,    0,    0,    0,  334,  321,  329,  316,
      491,  690,  495,  339,  300,  288,    0,  298,  287,  289,
      290,  285,  273,  274,  256,  262,  249,  242,  240,  238,
      244,  241,  229,  210,  215,  195,  193,  199,  178,  175,
      203,  171,  151,  145,  151,  147,  130,  145,  123,  109,

      102,   77,   65,  690,  690,  690,  552,  554,  556,  102,
      558
    } ;

static const flex_int16_t yy_def[412] =
    {   0,
      406,    1,  407,  407,  408,  408,  409,  409,  406,  406,
      406,  406,  406,  406,  406,  410,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  410,  410,  406,  406,  406,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  406,  406,  406,  406,  406,  406,
      406,  411,  406,  406,  406,  406,  406,  406,  406,  406,
      410,  406,  406,  406,  406,   75,  406,  406,  406,  406,
      406,  406,  406,   28,  406,  406,   28,  406,  406,  406,
      406,  406,  410,  410,  410,  406,  410,  410,  410,  410,

      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  406,  406,  406,  406,
      406,  406,  406,   75,  406,  406,   76,  145,  406,  406,
      406,  406,  406,  406,   83,  406,  406,  155,   85,  155,
       85,   85,   85,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,

      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      406,  406,  406,  406,  145,  145,  148,  148,  148,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  155,
      156,  406,  156,  156,  156,   85,  160,  156,  237,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  237,  238,  238,  238,  238,

      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  406,  406,  406,  406,  406,  406,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  410,  410,  410,  410,
      406,  406,  406,  410,  406,  410,  410,  410,  410,  410,
      410,  410,  410,  410,  410,  410,  406,  406,  410,  410,
      410,  410,  410,  410,  406,  406,  410,  410,  410,  406,
      406,  410,  406,  406,  410,  406,  406,  406,  406,  406,

      406,  406,  406,  406,  406,    0,  406,  406,  406,  406,
      406
    } ;

static const flex_int16_t yy_nxt[749] =
    {   0,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
       20,   21,   22,   23,   24,   25,   26,   27,   28,   29,
       30,   31,   32,   16,   33,   34,   35,   10,   36,   37,
       38,   39,   40,   41,   42,   43,   44,   45,   16,   46,
       16,   47,   16,   48,   16,   49,   50,   51,   52,   16,
       53,   54,   16,   16,   16,   55,   56,   57,   59,   60,
       64,   61,   59,   60,   64,   61,   68,   68,   73,   65,
       68,   68,  258,   65,   78,  259,   74,   75,   75,   79,
       88,   89,   80,   62,   81,   81,   94,   62,   91,   92,
       76,   95,   96,   98,   97,   97,  100,   81,  101,  103,

      121,   77,  107,   71,  122,  102,  104,   97,   99,  105,
      194,  108,  106,  405,  117,  195,   76,  109,  123,  110,
      118,  119,  124,   81,   82,  404,   82,   83,  111,   84,
       85,  112,   68,   81,  139,   86,   68,  125,  128,  113,
      126,  114,   87,  204,  115,  403,  133,   86,  129,  130,
      205,  131,  402,  132,  134,   96,  139,   81,   81,  147,
      148,  150,  401,  151,  152,  140,   75,   75,   87,  400,
       81,   96,  140,   81,   81,  140,  399,  140,   82,   76,
       82,  150,  398,  151,  152,  185,   81,  172,  173,   96,
      397,   97,   97,  188,  189,  199,  137,  142,  396,  142,

      143,  206,  144,  145,   97,   76,  395,  208,  146,  209,
      200,   96,   81,   81,   81,   76,  213,  213,  394,  207,
      146,  393,  143,  185,  211,  212,   81,  218,  219,  213,
       81,  142,  392,  142,  143,  185,  211,  212,  221,  221,
      185,   76,  153,  391,  153,  154,  390,  155,  156,  230,
      231,  221,   81,  157,  222,  213,  223,  224,  185,  154,
      158,  226,  227,  229,  229,  157,  249,  250,  389,  225,
      296,  297,  237,  238,  228,  185,  229,  221,  153,  185,
      153,  154,  388,  226,  227,  239,  158,   82,  387,   82,
      160,  386,  161,  162,  385,  225,  228,  185,   86,  384,

      228,  280,  229,  281,  282,  163,  284,  284,  285,  285,
       86,  239,  287,  287,  288,  288,  283,  383,  185,  213,
      382,  285,  228,  381,  380,  221,  222,  288,  223,  223,
      379,  163,  142,  185,  142,  214,  185,  215,  216,  289,
      289,  225,  283,  146,  378,  213,  222,  285,  223,  224,
      217,  221,  228,  288,  377,  146,  222,  376,  223,  223,
      154,  225,  289,  289,  375,  374,  290,  225,  291,  292,
      373,  225,  294,  294,  372,  228,  217,  153,  228,  153,
      232,  293,  233,  234,  185,  229,  185,  225,  157,  295,
      295,  298,  299,  332,  332,  235,  371,  225,  370,  369,

      157,  228,  295,  185,  300,  185,  332,  293,  185,  368,
      280,  229,  281,  281,  280,  367,  281,  282,  284,  284,
      280,  235,  281,  281,  366,  283,  333,  333,  295,  283,
      300,  213,  332,  287,  287,  283,  335,  335,  365,  285,
      289,  289,  364,  336,  336,  290,  221,  291,  291,  288,
      362,  283,  360,  228,  359,  283,  336,  213,  294,  294,
      293,  283,  185,  358,  185,  285,  290,  357,  291,  292,
      356,  229,  221,  355,  290,  288,  291,  291,  354,  228,
      353,  293,  336,  337,  337,  352,  293,  361,  361,  293,
      333,  333,  335,  335,  351,  185,  295,  229,  363,  363,

      332,  337,  337,  285,  350,  288,  349,  293,  361,  361,
      185,  336,  363,  363,  295,  293,  348,  347,  346,  345,
      344,  332,  295,  343,  342,  336,  332,  185,  341,  285,
      340,  288,  339,  338,  334,  331,  330,  336,  329,  328,
      295,  327,  326,  185,  325,  324,  185,  332,  323,  322,
      321,  336,   58,   58,   63,   63,   66,   66,  138,  138,
      320,  319,  318,  317,  316,  315,  314,  185,  313,  312,
      311,  310,  309,  308,  185,  307,  185,  185,  306,  305,
      304,  303,  302,  301,  236,  286,  143,  279,  278,  277,
      276,  275,  274,  185,  273,  272,  271,  270,  269,  268,

      267,  266,  265,  264,  263,  185,  262,  185,  261,  260,
      185,  257,  256,  255,  254,  185,  253,  252,  251,  248,
      185,  247,  185,  185,  246,  245,  244,  243,  242,  241,
      240,  236,  236,  236,  150,  220,  210,  203,  202,  201,
      198,  197,  196,  193,  192,  185,  191,  190,  187,  186,
      185,  184,  183,  182,  181,  180,  179,  178,  177,  176,
      175,  174,  171,  170,  169,  168,  167,  166,  165,  164,
      159,  159,  149,  141,  138,  136,  135,  127,  120,  116,
       93,   90,   73,   72,   70,   69,  406,   67,   67,    9,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,

      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406
    } ;

static const flex_int16_t yy_chk[749] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    3,    3,
        5,    3,    4,    4,    6,    4,   11,   15,   24,    5,
       11,   15,  187,    6,   26,  187,   24,   25,   25,   26,
       30,   30,   27,    3,   27,   27,   34,    4,   32,   32,
       25,   34,   38,   39,   38,   38,   40,   27,   40,   41,

       48,   25,   42,  410,   48,   40,   41,   38,   39,   41,
      125,   42,   41,  403,   46,  125,   25,   43,   48,   43,
       46,   46,   49,   27,   28,  402,   28,   28,   43,   28,
       28,   44,   68,   38,   62,   28,   68,   49,   51,   44,
       49,   44,   28,  133,   44,  401,   52,   28,   51,   51,
      133,   51,  400,   51,   52,   56,   62,   56,   56,   76,
       76,   82,  399,   82,   82,   62,   80,   80,   28,  398,
       56,   81,   62,   81,   81,   62,  397,   62,   86,   80,
       86,   86,  396,   86,   86,  395,   81,  103,  103,   97,
      394,   97,   97,  119,  119,  129,   56,   75,  393,   75,

       75,  134,   75,   75,   97,   80,  392,  135,   75,  135,
      129,  137,   81,  137,  137,   75,  143,  143,  391,  134,
       75,  390,  142,  134,  142,  142,  137,  148,  148,  143,
       97,  146,  389,  146,  146,  388,  146,  146,  150,  150,
      387,   75,   83,  386,   83,   83,  385,   83,   83,  155,
      155,  150,  137,   83,  152,  143,  152,  152,  384,  153,
       83,  153,  153,  154,  154,   83,  176,  176,  383,  152,
      237,  237,  160,  160,  153,  382,  154,  150,  157,  381,
      157,  157,  380,  157,  157,  160,   83,   85,  379,   85,
       85,  378,   85,   85,  377,  152,  157,  376,   85,  375,

      153,  212,  154,  212,  212,   85,  213,  213,  214,  214,
       85,  160,  221,  221,  222,  222,  212,  374,  373,  213,
      372,  214,  157,  371,  370,  221,  223,  222,  223,  223,
      369,   85,  145,  368,  145,  145,  366,  145,  145,  228,
      228,  223,  212,  145,  365,  213,  224,  214,  224,  224,
      145,  221,  228,  222,  364,  145,  225,  360,  225,  225,
      226,  224,  226,  226,  359,  358,  227,  223,  227,  227,
      357,  225,  229,  229,  353,  226,  145,  156,  228,  156,
      156,  227,  156,  156,  352,  229,  351,  224,  156,  232,
      232,  238,  238,  280,  280,  156,  350,  225,  349,  348,

      156,  226,  232,  347,  238,  346,  280,  227,  344,  343,
      281,  229,  281,  281,  282,  342,  282,  282,  284,  284,
      283,  156,  283,  283,  341,  281,  285,  285,  232,  282,
      238,  284,  280,  287,  287,  283,  288,  288,  340,  285,
      289,  289,  338,  290,  290,  291,  287,  291,  291,  288,
      334,  281,  330,  289,  329,  282,  290,  284,  294,  294,
      291,  283,  328,  327,  326,  285,  292,  325,  292,  292,
      324,  294,  287,  323,  293,  288,  293,  293,  322,  289,
      321,  292,  290,  295,  295,  320,  291,  332,  332,  293,
      333,  333,  335,  335,  319,  318,  295,  294,  336,  336,

      332,  337,  337,  333,  317,  335,  316,  292,  361,  361,
      315,  336,  363,  363,  337,  293,  314,  313,  311,  310,
      309,  361,  295,  308,  306,  363,  332,  305,  304,  333,
      303,  335,  302,  301,  286,  279,  278,  336,  275,  274,
      337,  273,  272,  271,  270,  269,  268,  361,  267,  266,
      265,  363,  407,  407,  408,  408,  409,  409,  411,  411,
      264,  263,  262,  261,  260,  259,  258,  257,  256,  255,
      254,  252,  251,  250,  249,  248,  247,  246,  245,  244,
      243,  242,  241,  240,  236,  220,  211,  210,  209,  208,
      207,  206,  205,  204,  203,  202,  201,  200,  199,  198,

      197,  196,  195,  194,  193,  192,  191,  190,  189,  188,
      186,  184,  183,  182,  181,  180,  179,  178,  177,  175,
      174,  173,  172,  171,  170,  169,  168,  167,  166,  165,
      164,  163,  161,  159,  151,  149,  136,  132,  131,  130,
      128,  127,  126,  124,  123,  122,  121,  120,  118,  116,
      115,  114,  113,  112,  111,  110,  109,  108,  107,  106,
      105,  104,  102,  101,  100,   99,   98,   95,   94,   93,
       87,   84,   77,   65,   60,   54,   53,   50,   47,   45,
       33,   31,   22,   18,   14,   13,    9,    8,    7,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,

      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
static int yy_more_flag = 0;
static int yy_more_len = 0;
#define yymore() ((yy_more_flag) = 1)
#define YY_MORE_ADJ (yy_more_len)
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "jucompiler.l"
#line 2 "jucompiler.l"
#include <stdio.h>
#include <stdlib.h>
    int nline = 1;
    int column = 1;
    int errors = 0;
    int state = 0;
    int errol = 1;
    int erroc = 1;

  void resetline(){
  	nline++;
	column=1;
}

    
#line 761 "lex.yy.c"
 
#line 763 "lex.yy.c"

#define INITIAL 0
#define STRING 1
#define COMMENT 2
#define COMMENT_1 3

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 36 "jucompiler.l"

#line 985 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		(yy_more_len) = 0;
		if ( (yy_more_flag) )
			{
			(yy_more_len) = (int) ((yy_c_buf_p) - (yytext_ptr));
			(yy_more_flag) = 0;
			}
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 407 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 690 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 37 "jucompiler.l"
{if (state==1)printf("RESERVED(%s)\n",yytext);column+=yyleng;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 39 "jucompiler.l"
{if (state==1)printf("INTLIT(0)\n");column+=yyleng;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 40 "jucompiler.l"
{if (state==1)printf("INTLIT(%s)\n",yytext);column+=yyleng;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 41 "jucompiler.l"
{if (state==1)printf("INTLIT(%s)\n",yytext);column+=yyleng;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 44 "jucompiler.l"
{if (state==1)printf("REALLIT(%s)\n",yytext);column+=yyleng;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 45 "jucompiler.l"
{if (state==1)printf("REALLIT(%s)\n",yytext);column+=yyleng;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 46 "jucompiler.l"
{if (state==1)printf("REALLIT(%s)\n",yytext);column+=yyleng;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 47 "jucompiler.l"
{if (state==1)printf("REALLIT(%s)\n",yytext);column+=yyleng;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 48 "jucompiler.l"
{if (state==1)printf("REALLIT(%s)\n",yytext);column+=yyleng;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 49 "jucompiler.l"
{if (state==1)printf("REALLIT(%s)\n",yytext);column+=yyleng;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 50 "jucompiler.l"
{if (state==1)printf("REALLIT(%s)\n",yytext);column+=yyleng;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 51 "jucompiler.l"
{if (state==1)printf("REALLIT(%s)\n",yytext);column+=yyleng;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 52 "jucompiler.l"
{if (state==1)printf("REALLIT(%s)\n",yytext);column+=yyleng;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 53 "jucompiler.l"
{if (state==1)printf("REALLIT(%s)\n",yytext);column+=yyleng;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 54 "jucompiler.l"
{if (state==1)printf("REALLIT(%s)\n",yytext);column+=yyleng;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 55 "jucompiler.l"
{if (state==1)printf("REALLIT(%s)\n",yytext);column+=yyleng;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 56 "jucompiler.l"
{if (state==1)printf("REALLIT(%s)\n",yytext);column+=yyleng;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 61 "jucompiler.l"
{BEGIN COMMENT_1;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 62 "jucompiler.l"

	YY_BREAK
case 20:
/* rule 20 can match eol */
YY_RULE_SETUP
#line 63 "jucompiler.l"
{BEGIN 0; resetline();}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 66 "jucompiler.l"
BEGIN COMMENT;errol = nline;erroc = column;column+=yyleng;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 67 "jucompiler.l"
BEGIN INITIAL;column+=yyleng;          //Finaliza o comentario
	YY_BREAK
case YY_STATE_EOF(COMMENT):
#line 68 "jucompiler.l"
{BEGIN 0;printf("Line %d, col %d: unterminated comment\n",errol, erroc);}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 69 "jucompiler.l"
column+=yyleng;
	YY_BREAK
case 24:
/* rule 24 can match eol */
YY_RULE_SETUP
#line 70 "jucompiler.l"
{resetline();}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 73 "jucompiler.l"
BEGIN(STRING);errors = 0;errol = nline;erroc = column;column+=yyleng;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 74 "jucompiler.l"
yymore();column+=1;
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 75 "jucompiler.l"
yymore();column+=2;
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 76 "jucompiler.l"
{yytext[yyleng-1] = '\0'; if(errors == 0 && state == 1){printf("STRLIT(\"%s\")\n",yytext);} BEGIN(0);column+=1;}
	YY_BREAK
case 29:
/* rule 29 can match eol */
YY_RULE_SETUP
#line 77 "jucompiler.l"
printf("Line %d,col %d: unterminated string literal\n",errol,erroc);BEGIN(0);resetline();
	YY_BREAK
case 30:
/* rule 30 can match eol */
YY_RULE_SETUP
#line 78 "jucompiler.l"
{printf("Line %d, col %d: invalid escape sequence (\\%c)\n",nline,column,yytext[yyleng-1]);errors = 1;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 82 "jucompiler.l"
{if (state==1)printf("WHILE\n");column+=yyleng;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 83 "jucompiler.l"
{if (state==1)printf("VOID\n");column+=yyleng;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 84 "jucompiler.l"
{if (state==1)printf("STRING\n");column+=yyleng;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 85 "jucompiler.l"
{if (state==1)printf("STATIC\n");column+=yyleng;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 86 "jucompiler.l"
{if (state==1)printf("RETURN\n");column+=yyleng;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 87 "jucompiler.l"
{if (state==1)printf("PUBLIC\n");column+=yyleng;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 88 "jucompiler.l"
{if (state==1)printf("PARSEINT\n");column+=yyleng;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 89 "jucompiler.l"
{if (state==1)printf("PRINT\n");column+=yyleng;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 90 "jucompiler.l"
{if (state==1)printf("INT\n");column+=yyleng;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 91 "jucompiler.l"
{if (state==1)printf("IF\n");column+=yyleng;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 92 "jucompiler.l"
{if (state==1)printf("ELSE\n");column+=yyleng;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 93 "jucompiler.l"
{if (state==1)printf("DOUBLE\n");column+=yyleng;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 94 "jucompiler.l"
{if (state==1)printf("DOTLENGTH\n");column+=yyleng;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 95 "jucompiler.l"
{if (state==1)printf("CLASS\n");column+=yyleng;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 96 "jucompiler.l"
{if (state==1)printf("BOOL\n");column+=yyleng;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 97 "jucompiler.l"
{if (state==1)printf("XOR\n");column+=yyleng;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 98 "jucompiler.l"
{if (state==1)printf("RSHIFT\n");column+=yyleng;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 99 "jucompiler.l"
{if (state==1)printf("LSHIFT\n");column+=yyleng;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 100 "jucompiler.l"
{if (state==1)printf("ARROW\n");column+=yyleng;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 101 "jucompiler.l"
{if (state==1)printf("SEMICOLON\n");column+=yyleng;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 102 "jucompiler.l"
{if (state==1)printf("RSQ\n");column+=yyleng;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 103 "jucompiler.l"
{if (state==1)printf("RPAR\n");column+=yyleng;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 104 "jucompiler.l"
{if (state==1)printf("RBRACE\n");column+=yyleng;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 105 "jucompiler.l"
{if (state==1)printf("PLUS\n");column+=yyleng;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 106 "jucompiler.l"
{if (state==1)printf("OR\n");column+=yyleng;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 107 "jucompiler.l"
{if (state==1)printf("NOT\n");column+=yyleng;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 108 "jucompiler.l"
{if (state==1)printf("NE\n");column+=yyleng;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 109 "jucompiler.l"
{if (state==1)printf("MOD\n");column+=yyleng;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 110 "jucompiler.l"
{if (state==1)printf("MINUS\n");column+=yyleng;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 111 "jucompiler.l"
{if (state==1)printf("LT\n");column+=yyleng;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 112 "jucompiler.l"
{if (state==1)printf("LSQ\n");column+=yyleng;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 113 "jucompiler.l"
{if (state==1)printf("LPAR\n");column+=yyleng;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 114 "jucompiler.l"
{if (state==1)printf("LE\n");column+=yyleng;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 115 "jucompiler.l"
{if (state==1)printf("LBRACE\n");column+=yyleng;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 116 "jucompiler.l"
{if (state==1)printf("GT\n");column+=yyleng;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 117 "jucompiler.l"
{if (state==1)printf("GE\n");column+=yyleng;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 118 "jucompiler.l"
{if (state==1)printf("EQ\n");column+=yyleng;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 119 "jucompiler.l"
{if (state==1)printf("DIV\n");column+=yyleng;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 120 "jucompiler.l"
{if (state==1)printf("COMMA\n");column+=yyleng;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 121 "jucompiler.l"
{if (state==1)printf("STAR\n");column+=yyleng;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 122 "jucompiler.l"
{if (state==1)printf("ASSIGN\n");column+=yyleng;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 123 "jucompiler.l"
{if (state==1)printf("AND\n");column+=yyleng;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 124 "jucompiler.l"
{if (state==1)printf("BOOLLIT(true)\n");column+=yyleng;}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 125 "jucompiler.l"
{if (state==1)printf("BOOLLIT(false)\n");column+=yyleng;}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 126 "jucompiler.l"
{if (state==1)printf("ID(%s)\n",yytext);column+=yyleng;}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 128 "jucompiler.l"
column+=yyleng;
	YY_BREAK
case 77:
/* rule 77 can match eol */
YY_RULE_SETUP
#line 129 "jucompiler.l"
{resetline();}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 130 "jucompiler.l"
{printf("Line %d, col %d: illegal character (%s)\n",nline,column,yytext);column+=yyleng;}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 132 "jucompiler.l"
ECHO;
	YY_BREAK
#line 1452 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(STRING):
case YY_STATE_EOF(COMMENT_1):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 407 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 407 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 406);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 132 "jucompiler.l"

int main(int argc, char *argv[ ]){
    if(argc==2){
        char * str = "-l";
        if(strcmp(argv[1],str)==0){
            state=1;
        }
    }
    yylex();
    return 0;
}

int yywrap(){
    return 1;
}

