
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	(yytext_ptr) -= (yy_more_len); \
	yyleng = (int) (yy_cp - (yytext_ptr)); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 71
#define YY_END_OF_BUFFER 72
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[345] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,   72,   70,
       68,   69,   69,   34,   54,   53,   36,   70,   40,   30,
       48,   32,   47,   37,   70,   46,    2,    4,   28,   38,
       49,   43,   53,   53,   39,   29,   24,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   42,   70,   31,   60,   56,   56,   55,
       58,   67,   66,   66,   67,   63,   62,   62,   69,   35,
       53,   50,    1,   27,    6,    0,    0,   64,   61,    5,
        0,    0,    0,    3,    3,    0,    0,   26,   41,   45,
       44,   25,   53,   53,   53,   53,   53,   53,   53,   53,

       53,   53,   53,   53,   53,    1,   53,   53,   53,   53,
       53,   53,   53,   53,   18,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   33,   56,   59,   57,   66,   65,
       62,    6,    0,    0,    7,    0,    5,    0,    8,    3,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       53,    1,   53,   53,   53,   17,   53,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,    7,    0,    0,

        5,    0,    8,    0,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   19,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       51,   10,   53,   53,    0,   53,   53,   53,   53,   53,
       53,   22,   53,   53,   53,   53,   52,    1,   53,   53,
       53,   53,   53,   53,   53,   53,   53,   53,   53,   53,
       53,   53,    1,   53,   53,    9,    0,   53,   11,    1,
       53,   53,   53,   53,   20,   53,   53,   53,   53,   53,
       53,   53,   53,   14,   13,   12,   53,   53,   53,   53,

       21,    1,    0,   53,   23,   53,   53,   53,   53,   53,
       53,   53,   53,   53,    0,    0,   53,   53,   53,   53,
       53,   53,    0,    0,   53,   53,   53,    0,    0,   53,
        0,    0,   53,    0,    0,    0,    0,    0,    0,    0,
        0,   15,   16,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    4,    5,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    6,    7,    8,    1,    9,   10,   11,    1,   12,
       13,   14,   15,   16,   17,   18,   19,   20,   21,   21,
       21,   21,   21,   21,   21,   21,   21,    1,   22,   23,
       24,   25,    1,    1,    9,    9,    9,    9,   26,    9,
        9,    9,   27,    9,    9,    9,    9,    9,    9,    9,
        9,    9,   28,    9,    9,    9,    9,    9,    9,    9,
       29,   30,   31,   32,   33,    1,   34,   35,   36,   37,

       38,   39,   40,   41,   42,    9,   43,   44,   45,   46,
       47,   48,    9,   49,   50,   51,   52,   53,   54,   55,
       56,   57,   58,   59,   60,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[61] =
    {   0,
        1,    1,    2,    1,    2,    1,    1,    1,    3,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    3,
        3,    1,    1,    1,    1,    3,    3,    3,    1,    1,
        1,    1,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    1,    1,    1
    } ;

static const flex_int16_t yy_base[350] =
    {   0,
        0,    0,   58,   59,   65,   66,   69,   70,  494,  495,
      495,  495,  490,  468,  495,    0,  495,  480,  495,  495,
      495,  475,  495,   59,   57,   67,   72,   76,  495,   76,
      465,   79,  442,   31,  495,  495,  495,   56,   64,   74,
       69,   73,   89,  440,   93,  439,   88,   78,  447,   93,
       88,  437,  442,  495,  423,  495,  495,  495,  478,  495,
      116,  495,  495,  477,  460,  495,  495,  475,  495,  495,
        0,  495,  495,  495,  130,  137,  439,  495,  495,  122,
      151,  158,  160,  165,  174,  176,  181,  495,  495,  495,
      495,  495,  425,  426,  424,  423,  422,  424,  432,  418,

      137,  434,  433,  420,  426,  412,  413,  410,  410,  416,
      413,  411,  408,  405,    0,  407,  154,  408,  402,  398,
      407,  414,  117,  414,  397,  400,  127,  398,  403,  398,
      157,  174,  169,  401,  495,  495,  495,  495,  495,  495,
      495,  196,  198,  200,  216,  396,  218,  207,  221,  225,
      403,  398,  388,  387,  399,  392,  401,  396,  395,  396,
      382,  380,  197,  395,  393,  389,  381,  387,  374,  389,
      388,    0,  374,  206,  369,  381,  378,  375,  372,  372,
      361,  362,  368,  359,  361,  358,  366,  369,  355,  369,
      354,  356,  356,  363,  363,  365,  354,  239,  241,  357,

      243,  245,  247,  250,  356,  349,  356,  344,  343,  353,
      347,  348,  338,  336,  344,  333,  340,    0,  337,  344,
      337,  329,  341,  329,  343,  327,  322,  340,  339,  334,
      329,  321,  318,  326,  331,  317,  329,  323,  309,  312,
        0,    0,  310,  322,  308,  320,  317,  311,  321,  303,
      319,    0,  306,  307,  312,  312,    0,  304,  302,  295,
      299,  305,  305,  302,  290,  304,  303,  292,  301,  285,
      294,  285,  283,  290,  289,    0,  289,  280,    0,  310,
      291,  280,  273,  273,    0,  273,  266,  283,  284,  285,
      280,  279,  265,    0,    0,    0,  276,  267,  275,  268,

      495,  293,  263,  258,    0,  270,  261,  268,  269,  266,
      255,  256,  255,  262,  251,  246,  246,  248,  244,  242,
      235,  224,  239,  206,  205,  213,  186,  183,  207,  185,
      165,  162,  153,  144,  125,  143,  124,  107,   95,   74,
       34,  495,  495,  495,  284,  287,  290,   62,  293
    } ;

static const flex_int16_t yy_def[350] =
    {   0,
      344,    1,  345,  345,  346,  346,  347,  347,  344,  344,
      344,  344,  344,  344,  344,  348,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  348,  348,  344,  344,  344,  348,  348,  348,
      348,  348,  348,  348,  348,  348,  348,  348,  348,  348,
      348,  348,  348,  344,  344,  344,  344,  344,  344,  344,
      349,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      348,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  348,  348,  348,  348,  348,  348,  348,  348,

      348,  348,  348,  348,  348,  348,  348,  348,  348,  348,
      348,  348,  348,  348,  348,  348,  348,  348,  348,  348,
      348,  348,  348,  348,  348,  348,  348,  348,  348,  348,
      348,  348,  348,  348,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      348,  348,  348,  348,  348,  348,  348,  348,  348,  348,
      348,  348,  348,  348,  348,  348,  348,  348,  348,  348,
      348,  348,  348,  348,  348,  348,  348,  348,  348,  348,
      348,  348,  348,  348,  348,  348,  348,  348,  348,  348,
      348,  348,  348,  348,  348,  348,  348,  344,  344,  344,

      344,  344,  344,  344,  348,  348,  348,  348,  348,  348,
      348,  348,  348,  348,  348,  348,  348,  348,  348,  348,
      348,  348,  348,  348,  348,  348,  348,  348,  348,  348,
      348,  348,  348,  348,  348,  348,  348,  348,  348,  348,
      348,  348,  348,  348,  344,  348,  348,  348,  348,  348,
      348,  348,  348,  348,  348,  348,  348,  348,  348,  348,
      348,  348,  348,  348,  348,  348,  348,  348,  348,  348,
      348,  348,  348,  348,  348,  348,  344,  348,  348,  348,
      348,  348,  348,  348,  348,  348,  348,  348,  348,  348,
      348,  348,  348,  348,  348,  348,  348,  348,  348,  348,

      344,  348,  344,  348,  348,  348,  348,  348,  348,  348,
      348,  348,  348,  348,  344,  344,  348,  348,  348,  348,
      348,  348,  344,  344,  348,  348,  348,  344,  344,  348,
      344,  344,  348,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,    0,  344,  344,  344,  344,  344
    } ;

static const flex_int16_t yy_nxt[556] =
    {   0,
       10,   11,   12,   11,   13,   11,   14,   15,   16,   17,
       18,   19,   20,   21,   22,   23,   24,   25,   26,   27,
       28,   29,   30,   31,   32,   16,   33,   34,   35,   10,
       36,   37,   16,   38,   39,   40,   41,   42,   43,   44,
       16,   45,   16,   46,   16,   47,   16,   48,   49,   50,
       51,   16,   52,   53,   16,   16,   16,   54,   55,   56,
       58,   58,   59,   59,   71,   60,   60,   63,   63,   64,
       64,   67,   67,   68,   68,   73,   75,   75,   65,   65,
       78,   94,   76,   74,  343,   79,   95,   61,   61,   80,
       96,   81,   81,   80,   76,   84,   85,   82,   88,   89,

       77,   82,   91,   92,   83,   97,  105,  101,   86,   82,
       98,  122,   99,   82,  102,  106,  107,  103,  108,  100,
      104,  119,  110,  138,  342,  120,  123,  109,  131,  124,
      111,  115,  112,  126,   87,  113,  132,  116,  117,  121,
      341,  147,  147,  127,  128,  138,  129,   76,  130,  142,
      142,  144,  340,  144,  138,   76,  145,  145,  181,   76,
      186,  138,  143,  182,  138,  339,  138,   76,   80,  338,
       81,   81,  148,  337,  148,  187,   82,  149,  149,   81,
       81,  336,   80,   83,   84,   84,  159,  160,   82,  172,
       82,   80,   83,   84,   85,   84,   84,   86,  191,   82,

      150,  150,   82,  175,  176,  192,   86,  193,   86,  335,
      195,   82,  196,   87,  334,  142,  142,  142,  142,  145,
      145,   76,  333,   87,  332,  194,  149,  149,  143,  172,
      143,  331,   87,   76,   87,  198,  198,  201,  201,   87,
      203,  203,  330,   76,  150,  150,  214,  215,  199,  223,
      202,  172,  224,  204,  172,   76,  329,   87,  198,  198,
      198,  198,  201,  201,  201,  201,  203,  203,   76,  203,
      203,  199,  328,  199,  172,  202,  327,  202,  172,  204,
       76,  172,  204,   87,   57,   57,   57,   62,   62,   62,
       66,   66,   66,  137,  326,  137,  325,  324,  323,  172,

      322,  321,  172,  320,  319,  318,  317,  172,  172,  316,
      315,  314,  313,  312,  311,  310,  172,  172,  309,  308,
      307,  172,  172,  172,  306,  305,  304,  303,  302,  301,
      300,  299,  172,  298,  172,  297,  296,  295,  294,  293,
      292,  291,  172,  290,  289,  172,  288,  287,  286,  285,
      284,  283,  282,  172,  281,  280,  279,  278,  277,  276,
      275,  274,  273,  272,  271,  172,  270,  269,  172,  268,
      267,  266,  265,  264,  263,  262,  261,  260,  259,  172,
      258,  257,  256,  255,  254,  253,  172,  252,  172,  172,
      251,  250,  249,  248,  247,  246,  245,  244,  243,  242,

      241,  240,  239,  172,  238,  237,  236,  235,  234,  233,
      232,  231,  230,  229,  228,  172,  227,  172,  226,  225,
      172,  222,  221,  220,  219,  172,  218,  217,  216,  213,
      172,  212,  172,  172,  211,  210,  209,  208,  207,  206,
      205,  200,  197,  190,  189,  188,  185,  184,  183,  180,
      179,  172,  178,  177,  174,  173,  172,  171,  170,  169,
      168,  167,  166,  165,  164,  163,  162,  161,  158,  157,
      156,  155,  154,  153,  152,  151,  146,  141,  140,  139,
      136,  135,  134,  133,  125,  118,  114,   93,   90,   73,
       72,   70,   69,  344,    9,  344,  344,  344,  344,  344,

      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344
    } ;

static const flex_int16_t yy_chk[556] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        3,    4,    3,    4,  348,    3,    4,    5,    6,    5,
        6,    7,    8,    7,    8,   24,   25,   25,    5,    6,
       26,   34,   25,   24,  341,   26,   34,    3,    4,   27,
       38,   27,   27,   28,   25,   28,   28,   27,   30,   30,

       25,   28,   32,   32,   27,   38,   41,   40,   28,   27,
       39,   48,   39,   28,   40,   41,   42,   40,   42,   39,
       40,   47,   43,   61,  340,   47,   48,   42,   51,   48,
       43,   45,   43,   50,   28,   43,   51,   45,   45,   47,
      339,   80,   80,   50,   50,   61,   50,   80,   50,   75,
       75,   76,  338,   76,   61,   75,   76,   76,  123,   80,
      127,   61,   75,  123,   61,  337,   61,   75,   81,  336,
       81,   81,   82,  335,   82,  127,   81,   82,   82,   83,
       83,  334,   84,   81,   84,   84,  101,  101,   81,  333,
       84,   85,   83,   85,   85,   86,   86,   84,  131,   85,

       87,   87,   84,  117,  117,  131,   85,  132,   86,  332,
      133,   85,  133,   87,  331,  142,  142,  143,  143,  144,
      144,  142,  330,   84,  329,  132,  148,  148,  142,  132,
      143,  328,   85,  142,   86,  145,  145,  147,  147,   87,
      149,  149,  327,  147,  150,  150,  163,  163,  145,  174,
      147,  326,  174,  149,  325,  147,  324,  150,  198,  198,
      199,  199,  201,  201,  202,  202,  203,  203,  201,  204,
      204,  198,  323,  199,  322,  201,  321,  202,  320,  203,
      201,  319,  204,  150,  345,  345,  345,  346,  346,  346,
      347,  347,  347,  349,  318,  349,  317,  316,  315,  314,

      313,  312,  311,  310,  309,  308,  307,  306,  304,  303,
      302,  300,  299,  298,  297,  293,  292,  291,  290,  289,
      288,  287,  286,  284,  283,  282,  281,  280,  278,  277,
      275,  274,  273,  272,  271,  270,  269,  268,  267,  266,
      265,  264,  263,  262,  261,  260,  259,  258,  256,  255,
      254,  253,  251,  250,  249,  248,  247,  246,  245,  244,
      243,  240,  239,  238,  237,  236,  235,  234,  233,  232,
      231,  230,  229,  228,  227,  226,  225,  224,  223,  222,
      221,  220,  219,  217,  216,  215,  214,  213,  212,  211,
      210,  209,  208,  207,  206,  205,  200,  197,  196,  195,

      194,  193,  192,  191,  190,  189,  188,  187,  186,  185,
      184,  183,  182,  181,  180,  179,  178,  177,  176,  175,
      173,  171,  170,  169,  168,  167,  166,  165,  164,  162,
      161,  160,  159,  158,  157,  156,  155,  154,  153,  152,
      151,  146,  134,  130,  129,  128,  126,  125,  124,  122,
      121,  120,  119,  118,  116,  114,  113,  112,  111,  110,
      109,  108,  107,  106,  105,  104,  103,  102,  100,   99,
       98,   97,   96,   95,   94,   93,   77,   68,   65,   64,
       59,   55,   53,   52,   49,   46,   44,   33,   31,   22,
       18,   14,   13,    9,  344,  344,  344,  344,  344,  344,

      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344,  344,  344,  344,  344,  344,
      344,  344,  344,  344,  344
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
static int yy_more_flag = 0;
static int yy_more_len = 0;
#define yymore() ((yy_more_flag) = 1)
#define YY_MORE_ADJ (yy_more_len)
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "jucompiler.l"
#line 2 "jucompiler.l"
#include <stdio.h>
#include <stdlib.h>
#include "functions.h"
#include "strutcs.h"
#include "y.tab.h"
    /*      Francisco Forte Nº2016225674
            Guilherme Costa Nº2017249276
    */

    extern int error_yacc;
    int nline = 1;
    int column = 1;
    int errors = 0;
    int state = 0;
    int parseState = 0;
    int errol = 1;
    int erroc = 1;
    extern program* programafinal;
  void resetline(){
  	nline++;
	column=1;
}

    
#line 705 "lex.yy.c"
 
#line 707 "lex.yy.c"

#define INITIAL 0
#define STRING 1
#define COMMENT 2
#define COMMENT_1 3

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 43 "jucompiler.l"

#line 929 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		(yy_more_len) = 0;
		if ( (yy_more_flag) )
			{
			(yy_more_len) = (int) ((yy_c_buf_p) - (yytext_ptr));
			(yy_more_flag) = 0;
			}
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 345 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 495 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 44 "jucompiler.l"
{if (state==1)printf("RESERVED(%s)\n",yytext);column+=yyleng;if(parseState==1) return RESERVED;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 46 "jucompiler.l"
{if (state==1)printf("INTLIT(0)\n");column+=yyleng;if(parseState==1){yylval.id=strdup(yytext); return INTLIT;}}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 47 "jucompiler.l"
{if (state==1)printf("INTLIT(%s)\n",yytext);column+=yyleng;if(parseState==1){yylval.id=strdup(yytext); return INTLIT;}}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 48 "jucompiler.l"
{if (state==1)printf("INTLIT(%s)\n",yytext);column+=yyleng;if(parseState==1){yylval.id=strdup(yytext); return INTLIT;}}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 51 "jucompiler.l"
{if (state==1)printf("REALLIT(%s)\n",yytext);column+=yyleng;if(parseState==1){yylval.id=strdup(yytext); return REALLIT;}}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 52 "jucompiler.l"
{if (state==1)printf("REALLIT(%s)\n",yytext);column+=yyleng;if(parseState==1){yylval.id=strdup(yytext); return REALLIT;}}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 53 "jucompiler.l"
{if (state==1)printf("REALLIT(%s)\n",yytext);column+=yyleng;if(parseState==1){yylval.id=strdup(yytext); return REALLIT;}}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 54 "jucompiler.l"
{if (state==1)printf("REALLIT(%s)\n",yytext);column+=yyleng;if(parseState==1){yylval.id=strdup(yytext); return REALLIT;}}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 56 "jucompiler.l"
{if (state==1)printf("WHILE\n");column+=yyleng;if(parseState==1) return WHILE;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 57 "jucompiler.l"
{if (state==1)printf("VOID\n");column+=yyleng;if(parseState==1) return VOID;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 58 "jucompiler.l"
{if (state==1)printf("STRING\n");column+=yyleng;if(parseState==1) return STRING1;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 59 "jucompiler.l"
{if (state==1)printf("STATIC\n");column+=yyleng;if(parseState==1) return STATIC;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 60 "jucompiler.l"
{if (state==1)printf("RETURN\n");column+=yyleng;if(parseState==1) return RETURN;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 61 "jucompiler.l"
{if (state==1)printf("PUBLIC\n");column+=yyleng;if(parseState==1) return PUBLIC;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 62 "jucompiler.l"
{if (state==1)printf("PARSEINT\n");column+=yyleng;if(parseState==1) return PARSEINT;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 63 "jucompiler.l"
{if (state==1)printf("PRINT\n");column+=yyleng;if(parseState==1) return PRINT;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 64 "jucompiler.l"
{if (state==1)printf("INT\n");column+=yyleng;if(parseState==1) return INT;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 65 "jucompiler.l"
{if (state==1)printf("IF\n");column+=yyleng;if(parseState==1) return IF;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 66 "jucompiler.l"
{if (state==1)printf("ELSE\n");column+=yyleng;if(parseState==1) return ELSE;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 67 "jucompiler.l"
{if (state==1)printf("DOUBLE\n");column+=yyleng;if(parseState==1) return DOUBLE;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 68 "jucompiler.l"
{if (state==1)printf("DOTLENGTH\n");column+=yyleng;if(parseState==1) return DOTLENGTH;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 69 "jucompiler.l"
{if (state==1)printf("CLASS\n");column+=yyleng;if(parseState==1) return CLASS;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 70 "jucompiler.l"
{if (state==1)printf("BOOL\n");column+=yyleng;if(parseState==1) return BOOL;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 71 "jucompiler.l"
{if (state==1)printf("XOR\n");column+=yyleng;if(parseState==1) return XOR;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 72 "jucompiler.l"
{if (state==1)printf("RSHIFT\n");column+=yyleng;if(parseState==1) return RSHIFT;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 73 "jucompiler.l"
{if (state==1)printf("LSHIFT\n");column+=yyleng;if(parseState==1) return LSHIFT;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 74 "jucompiler.l"
{if (state==1)printf("ARROW\n");column+=yyleng;if(parseState==1) return ARROW;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 75 "jucompiler.l"
{if (state==1)printf("SEMICOLON\n");column+=yyleng;if(parseState==1) return SEMICOLON;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 76 "jucompiler.l"
{if (state==1)printf("RSQ\n");column+=yyleng;if(parseState==1) return RSQ;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 77 "jucompiler.l"
{if (state==1)printf("RPAR\n");column+=yyleng;if(parseState==1) return RPAR;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 78 "jucompiler.l"
{if (state==1)printf("RBRACE\n");column+=yyleng;if(parseState==1) return RBRACE;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 79 "jucompiler.l"
{if (state==1)printf("PLUS\n");column+=yyleng;if(parseState==1) return PLUS;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 80 "jucompiler.l"
{if (state==1)printf("OR\n");column+=yyleng;if(parseState==1) return OR;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 81 "jucompiler.l"
{if (state==1)printf("NOT\n");column+=yyleng;if(parseState==1) return NOT;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 82 "jucompiler.l"
{if (state==1)printf("NE\n");column+=yyleng;if(parseState==1) return NE;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 83 "jucompiler.l"
{if (state==1)printf("MOD\n");column+=yyleng;if(parseState==1) return MOD;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 84 "jucompiler.l"
{if (state==1)printf("MINUS\n");column+=yyleng;if(parseState==1) return MINUS;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 85 "jucompiler.l"
{if (state==1)printf("LT\n");column+=yyleng;if(parseState==1) return LT;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 86 "jucompiler.l"
{if (state==1)printf("LSQ\n");column+=yyleng;if(parseState==1) return LSQ;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 87 "jucompiler.l"
{if (state==1)printf("LPAR\n");column+=yyleng;if(parseState==1) return LPAR;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 88 "jucompiler.l"
{if (state==1)printf("LE\n");column+=yyleng;if(parseState==1) return LE;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 89 "jucompiler.l"
{if (state==1)printf("LBRACE\n");column+=yyleng;if(parseState==1) return LBRACE;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 90 "jucompiler.l"
{if (state==1)printf("GT\n");column+=yyleng;if(parseState==1) return GT;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 91 "jucompiler.l"
{if (state==1)printf("GE\n");column+=yyleng;if(parseState==1) return GE;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 92 "jucompiler.l"
{if (state==1)printf("EQ\n");column+=yyleng;if(parseState==1) return EQ;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 93 "jucompiler.l"
{if (state==1)printf("DIV\n");column+=yyleng;if(parseState==1) return DIV;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 94 "jucompiler.l"
{if (state==1)printf("COMMA\n");column+=yyleng;if(parseState==1) return COMMA;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 95 "jucompiler.l"
{if (state==1)printf("STAR\n");column+=yyleng;if(parseState==1) return STAR;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 96 "jucompiler.l"
{if (state==1)printf("ASSIGN\n");column+=yyleng;if(parseState==1) return ASSIGN;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 97 "jucompiler.l"
{if (state==1)printf("AND\n");column+=yyleng;if(parseState==1) return AND;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 98 "jucompiler.l"
{if (state==1)printf("BOOLLIT(true)\n");column+=yyleng;if(parseState==1) return TRUE;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 99 "jucompiler.l"
{if (state==1)printf("BOOLLIT(false)\n");column+=yyleng;if(parseState==1) return FALSE;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 100 "jucompiler.l"
{if (state==1)printf("ID(%s)\n",yytext);column+=yyleng;if(parseState==1){yylval.id=strdup(yytext); return ID;}}
	YY_BREAK
case YY_STATE_EOF(STRING):
#line 102 "jucompiler.l"
{if(parseState==1)column++;printf("Line %d, col %d: unterminated string literal\n",errol,erroc);yyterminate();}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 103 "jucompiler.l"
{BEGIN(STRING);errors = 0;errol = nline;erroc = column;column+=yyleng;if(parseState==1)yymore();}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 104 "jucompiler.l"
{BEGIN 0; column+=1;if(errors == 0 && state == 1){printf("STRLIT(\"%s)\n",yytext);}if(parseState==1 && errors == 0){yylval.id=strdup(yytext);return STRLIT;}}
	YY_BREAK
case 56:
/* rule 56 can match eol */
YY_RULE_SETUP
#line 105 "jucompiler.l"
{printf("Line %d, col %d: unterminated string literal\n",errol,erroc);BEGIN 0;resetline();}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 106 "jucompiler.l"
{yymore();column+=2;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 107 "jucompiler.l"
{printf("Line %d, col %d: invalid escape sequence (\\)\n",nline,column);errors = 1;column+=1;if(parseState==1)yymore();}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 108 "jucompiler.l"
{printf("Line %d, col %d: invalid escape sequence (\\%c)\n",nline,column,yytext[yyleng - 1]);errors = 1;column+=2;if(parseState==1)yymore();}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 109 "jucompiler.l"
{yymore();column+=1;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 111 "jucompiler.l"
{BEGIN COMMENT_1;}
	YY_BREAK
case 62:
/* rule 62 can match eol */
YY_RULE_SETUP
#line 112 "jucompiler.l"
{BEGIN 0; resetline();}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 113 "jucompiler.l"

	YY_BREAK
case YY_STATE_EOF(COMMENT):
#line 115 "jucompiler.l"
{if(parseState==1)column++;printf("Line %d, col %d: unterminated comment\n",errol, erroc);yyterminate();} 
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 116 "jucompiler.l"
{BEGIN COMMENT;errol = nline;erroc = column;column+=yyleng;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 117 "jucompiler.l"
{BEGIN INITIAL;column+=yyleng;}
	YY_BREAK
case 66:
/* rule 66 can match eol */
YY_RULE_SETUP
#line 118 "jucompiler.l"
{resetline();}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 119 "jucompiler.l"
{column+=yyleng;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 121 "jucompiler.l"
{column+=yyleng;}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(COMMENT_1):
#line 122 "jucompiler.l"
{column+=1;yyterminate();}
	YY_BREAK
case 69:
/* rule 69 can match eol */
YY_RULE_SETUP
#line 123 "jucompiler.l"
{resetline();}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 127 "jucompiler.l"
{printf("Line %d, col %d: illegal character (%s)\n",nline,column,yytext);column+=yyleng;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 129 "jucompiler.l"
ECHO;
	YY_BREAK
#line 1364 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 345 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 345 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 344);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 129 "jucompiler.l"

void yyerror(char *msg) {
    printf("Line %d, col %d: %s: %s\n",nline,column-yyleng,msg, yytext);
}


int main(int argc, char *argv[ ]){
    if(argc==2){
        char *nStr = "-e1";
        char * str = "-l";
        char * parseStr = "-t";
        char * nParseStr = "-e2";
        if(strcmp(argv[1],str)==0){
			state=1;
			yylex();
			return 0;
        }
        else if(strcmp(argv[1],nStr)==0){
			state=0;
			yylex();
        }
        else if(strcmp(argv[1], parseStr)==0){
            parseState=1;
            if(yyparse() == 0) {
                if(error_yacc == 0){
                    printTree(programafinal);
                }
            }
        }
        else if(strcmp(argv[1], nParseStr)==0){
            parseState=1;
            yyparse();
        }
    }
    else{
        parseState=1;
        yyparse();
    }
    return 0;
}

int yywrap(){
    return 1;
}

